// Real UK postcode -> delivery-day reference data (transcribed from the
// courier's weekly schedule photos), loaded once on first run so the
// Delivery Checker has something useful immediately. Review/correct it
// any time from Delivery Checker -> Manage Schedule.

const DAILY_GROUPS: [string, string][] = [
  ["KT", "Kingston upon Thames"], ["CR", "Croydon"], ["SM", "Sutton"], ["BR", "Bromley"],
  ["DA", "Dartford"], ["TW", "Twickenham"], ["SW", "London SW"], ["SE", "London SE"],
  ["W", "London W"], ["EC", "London EC"], ["UB", "Southall"], ["HA", "Harrow"],
  ["NW", "London NW"], ["WC", "London WC"], ["WD", "Watford"], ["N", "London N"],
  ["EN", "Enfield"], ["E", "London E"], ["IG", "Ilford"], ["RM", "Romford"],
  ["SL", "Slough"], ["SS", "Southend-on-Sea"], ["AL", "St Albans"],
  ["WF", "Wakefield"], ["BD", "Bradford"], ["LS", "Leeds"], ["HD", "Huddersfield"],
  ["HX", "Halifax"], ["ST", "Stoke-on-Trent"], ["CW", "Crewe"], ["M", "Manchester"],
  ["OL", "Oldham"], ["SK", "Stockport"], ["DN", "Doncaster"], ["PR", "Preston"],
  ["FY", "Blackpool"], ["CH", "Chester"], ["L", "Liverpool"], ["BB", "Blackburn"],
  ["BL", "Bolton"], ["S", "Sheffield"],
];
const ALL_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const ROTATING_SCHEDULE: [string, string, string[]][] = [
  ["CM", "Chelmsford", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]],
  ["CO", "Colchester", ["Tuesday", "Friday"]],
  ["IP", "Ipswich", ["Tuesday", "Friday"]],
  ["NR", "Norwich", ["Tuesday"]],
  ["CB", "Cambridge", ["Tuesday", "Friday"]],
  ["PE", "Peterborough", ["Tuesday", "Friday"]],
  ["OX", "Oxford", ["Tuesday", "Friday"]],
  ["RG", "Reading", ["Tuesday", "Friday"]],
  ["SN", "Swindon", ["Tuesday", "Friday"]],
  ["HP", "Hemel Hempstead", ["Tuesday", "Friday"]],
  ["SP", "Salisbury", ["Tuesday"]],
  ["DT", "Dorchester", ["Tuesday"]],
  ["BA", "Bath", ["Tuesday"]],
  ["TA", "Taunton", ["Tuesday"]],
  ["EX", "Exeter", ["Tuesday"]],
  ["PL", "Plymouth", ["Tuesday"]],
  ["TQ", "Torquay", ["Tuesday"]],
  ["TR", "Truro", ["Tuesday"]],
  ["BH", "Bournemouth", ["Tuesday"]],
  ["NG", "Nottingham", ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday"]],
  ["DE", "Derby", ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday"]],
  ["BS", "Bristol", ["Tuesday", "Friday"]],
  ["NP", "Newport", ["Tuesday", "Friday"]],
  ["CF", "Cardiff", ["Tuesday", "Friday"]],
  ["GL", "Gloucester", ["Tuesday", "Friday"]],
  ["WR", "Worcester", ["Tuesday", "Friday"]],
  ["SA", "Swansea", ["Tuesday", "Friday"]],
  ["HR", "Hereford", ["Tuesday", "Friday"]],
  ["SO", "Southampton", ["Tuesday"]],
  ["PO", "Portsmouth", ["Tuesday"]],
  ["GU", "Guildford", ["Monday", "Tuesday"]],
  ["SY", "Shrewsbury", ["Tuesday", "Saturday"]],
  ["TF", "Telford", ["Tuesday", "Saturday"]],
  ["TS", "Teesside", ["Monday", "Friday"]],
  ["DL", "Darlington", ["Monday", "Friday"]],
  ["SR", "Sunderland", ["Monday", "Friday"]],
  ["DH", "Durham", ["Monday", "Friday"]],
  ["NE", "Newcastle", ["Monday", "Friday"]],
  ["HG", "Harrogate", ["Monday", "Friday"]],
  ["LU", "Luton", ["Monday", "Wednesday", "Thursday", "Saturday"]],
  ["MK", "Milton Keynes", ["Monday", "Wednesday", "Thursday", "Saturday"]],
  ["NN", "Northampton", ["Monday", "Wednesday", "Thursday", "Saturday"]],
  ["SG", "Stevenage", ["Monday", "Wednesday", "Saturday"]],
  ["CV", "Coventry", ["Monday", "Wednesday", "Saturday"]],
  ["LE", "Leicester", ["Monday", "Wednesday", "Thursday", "Saturday"]],
  ["B", "Birmingham", ["Monday", "Wednesday", "Saturday"]],
  ["WS", "Walsall", ["Monday", "Wednesday", "Saturday"]],
  ["WV", "Wolverhampton", ["Monday", "Wednesday", "Saturday"]],
  ["ME", "Medway", ["Monday", "Thursday"]],
  ["CT", "Canterbury", ["Monday", "Thursday"]],
  ["TN", "Tonbridge", ["Monday", "Thursday"]],
  ["RH", "Redhill", ["Monday", "Thursday"]],
  ["BN", "Brighton", ["Monday", "Thursday"]],
  ["FK", "Falkirk", ["Monday", "Friday"]],
  ["G", "Glasgow", ["Monday", "Friday"]],
  ["EH", "Edinburgh", ["Monday", "Friday"]],
  ["DG", "Dumfries", ["Monday", "Friday"]],
  ["KA", "Kilmarnock", ["Monday", "Friday"]],
  ["ML", "Motherwell", ["Monday", "Friday"]],
  ["CA", "Carlisle", ["Friday"]],
  ["HU", "Hull", ["Monday", "Wednesday", "Thursday", "Friday"]],
  ["YO", "York", ["Monday", "Wednesday", "Thursday", "Friday"]],
  ["LN", "Lincoln", ["Monday", "Wednesday", "Thursday", "Friday"]],
];

export const DELIVERY_SCHEDULE_SEED: { postcodePrefix: string; areaName: string; days: string[] }[] = [
  ...DAILY_GROUPS.map(([postcodePrefix, areaName]) => ({ postcodePrefix, areaName, days: ALL_DAYS })),
  ...ROTATING_SCHEDULE.map(([postcodePrefix, areaName, days]) => ({ postcodePrefix, areaName, days })),
];
